In [1]:
import statistics
ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
print( "ages =",ages)
ages.sort()
print("sorted ages =",ages)
maximum=max(ages)
print("maximum=",maximum)
minimum=min(ages)
print("minimum=",minimum)
ages.append(maximum)
print(ages)
ages.append(minimum)
print(ages)
median=statistics.median(ages)
print("median=",median)
average=statistics.mean(ages)
print("average=",average)
range=maximum-minimum
print("range=",range)

ages = [19, 22, 19, 24, 20, 25, 26, 24, 25, 24]
sorted ages = [19, 19, 20, 22, 24, 24, 24, 25, 25, 26]
maximum= 26
minimum= 19
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 26]
[19, 19, 20, 22, 24, 24, 24, 25, 25, 26, 26, 19]
median= 24.0
average= 22.75
range= 7


In [2]:
dog={}
print(dog)
dog={'name':'doggy','color':'black','breed':'german','legs':2,'age':5}
print(dog)
student={'first_name':'spandana','last_name':'vegi', 'gender':'female', 'age':21,'marital status':'single',
'skills':['JavaScript', 'r','clay art','Python'],'country':'USA', 'city':'kansas', 'address':'leawood'}
print(student)
print("length :",len(student))
print(student['skills'])
print(type(student['skills']))
student['skills'].append('reading')
print(student)
student_keys=student.keys()
print("student_keys=", student_keys)
student_values=student.values()
print("student_values=",student_values)

{}
{'name': 'doggy', 'color': 'black', 'breed': 'german', 'legs': 2, 'age': 5}
{'first_name': 'spandana', 'last_name': 'vegi', 'gender': 'female', 'age': 21, 'marital status': 'single', 'skills': ['JavaScript', 'r', 'clay art', 'Python'], 'country': 'USA', 'city': 'kansas', 'address': 'leawood'}
length : 9
['JavaScript', 'r', 'clay art', 'Python']
<class 'list'>
{'first_name': 'spandana', 'last_name': 'vegi', 'gender': 'female', 'age': 21, 'marital status': 'single', 'skills': ['JavaScript', 'r', 'clay art', 'Python', 'reading'], 'country': 'USA', 'city': 'kansas', 'address': 'leawood'}
student_keys= dict_keys(['first_name', 'last_name', 'gender', 'age', 'marital status', 'skills', 'country', 'city', 'address'])
student_values= dict_values(['spandana', 'vegi', 'female', 21, 'single', ['JavaScript', 'r', 'clay art', 'Python', 'reading'], 'USA', 'kansas', 'leawood'])


In [2]:
brothers=('kowshik','kumar','mani')
print("brothers =",brothers)
sisters=('alekhya','shaithi','mounika')
print("sisters=",sisters)
sibilings = brothers+sisters
print("sibilings=",sibilings)
length=len(sibilings)
print("length=",length)
lst_sibilings = tuple(sibilings)
print("lst_sibilings=",lst_sibilings)
parents=('mother','father')
family_members=lst_sibilings + parents
print("family_members=",family_members)

brothers = ('kowshik', 'kumar', 'mani')
sisters= ('alekhya', 'shaithi', 'mounika')
sibilings= ('kowshik', 'kumar', 'mani', 'alekhya', 'shaithi', 'mounika')
length= 6
lst_sibilings= ('kowshik', 'kumar', 'mani', 'alekhya', 'shaithi', 'mounika')
family_members= ('kowshik', 'kumar', 'mani', 'alekhya', 'shaithi', 'mounika', 'mother', 'father')


In [4]:
it_companies = {'Facebook', 'Google', 'Microsoft', 'Apple', 'IBM', 'Oracle', 'Amazon'}
A = {19, 22, 24, 20, 25, 26}
B = {19, 22, 20, 25, 26, 24, 28, 27}
age = [22, 19, 24, 25, 26, 24, 25, 24]
print("length of it_companies=",len(it_companies))
it_companies.add('Twitter')
print(it_companies)
it_companies.update(['cresn','matriczs','goldflex'])
print(it_companies)
it_companies.remove('Amazon')
print(it_companies)
print("Difference between Remove() and Discard(): \nDiscard() method is different from the remove() method, because the remove() method will throw an error if the specified item is not present in list, whereasthe discard() method will not throw any error if item doesn't exist in list");
join=A.union(B)
print("join",join)
intersection=A.intersection(B)
print("intersection",intersection)
print("subset=",A.issubset(B))
print("disjoint_sets=",A.isdisjoint(B))
join1=A.union(B)
print("joina&b",join1)
join2=B.union(A)
print("joinb&a",join2)
symmetric_difference=A.symmetric_difference(B)
print("symmetric_difference",symmetric_difference)
del(A)
del(B)
length_age=len(age)
print("age of list is ",length_age)
age_set=set(age)
print("age_set",age_set)
length_set=len(age_set)
print("length_set",length_set)
if length_age==length_set :
    {
        print("true")
    }
else:
    print("false")


#value= length_age==(length_set):true:false
#print(value)

length of it_companies= 7
{'Apple', 'IBM', 'Google', 'Amazon', 'Microsoft', 'Facebook', 'Oracle', 'Twitter'}
{'Google', 'Microsoft', 'Twitter', 'Amazon', 'Facebook', 'goldflex', 'IBM', 'cresn', 'Oracle', 'matriczs', 'Apple'}
{'Google', 'Microsoft', 'Twitter', 'Facebook', 'goldflex', 'IBM', 'cresn', 'Oracle', 'matriczs', 'Apple'}
Difference between Remove() and Discard(): 
Discard() method is different from the remove() method, because the remove() method will throw an error if the specified item is not present in list, whereasthe discard() method will not throw any error if item doesn't exist in list
join {19, 20, 22, 24, 25, 26, 27, 28}
intersection {19, 20, 22, 24, 25, 26}
subset= True
disjoint_sets= False
joina&b {19, 20, 22, 24, 25, 26, 27, 28}
joinb&a {19, 20, 22, 24, 25, 26, 27, 28}
symmetric_difference {27, 28}
age of list is  8
age_set {19, 22, 24, 25, 26}
length_set 5
false


In [5]:
r=30
_area_of_circle_ = 3.14*r*r
print("area =",_area_of_circle_)
_circum_of_circle_ =2*3.148*r
print("circumference=", _circum_of_circle_);
radius = int(input("Enter your value of radius: "))
print("radius =",radius)
area=3.14*radius*radius
print("area=",area)

area = 2826.0
circumference= 188.88
Enter your value of radius: 5
radius = 5
area= 78.5


In [6]:



string ="I am a teacher and I love to inspire and teach people"

wordlist = string.split(' ')
word_count=0
for word in wordlist:
    if wordlist.count(word) > 1:
        wordlist.remove(word)
        
    
    
    
print(wordlist)
print(len(wordlist))
#print(wordlist.count)


['am', 'a', 'teacher', 'I', 'love', 'to', 'inspire', 'and', 'teach', 'people']
10


In [7]:
#Question 7
text = "Name \t Age \tCountry City\nAsabench 250 \tFinland Helsinki"
print(text)


Name 	 Age 	Country City
Asabench 250 	Finland Helsinki


In [8]:
#Question 8
radius = 10
area = 3.14 * radius * radius
print("The area of a circle with radius",radius,"is %.0f" %area, "m")

The area of a circle with radius 10 is 314 m


In [2]:
#Question 9

Students_Lst_Lbs=[]
prmt = int(input("Enter number of students: "))
Students_Lst_Kgs=[]

for i in range(0,prmt):
    Students_Lst_Lbs.append(int(input()))
    Students_Lst_Kgs.append(Students_Lst_Lbs[i]*0.453592)
print(Students_Lst_Lbs)    
print(Students_Lst_Kgs)



Enter number of students: 4
140
145
150
155
[140, 145, 150, 155]
[63.50288, 65.77083999999999, 68.0388, 70.30676]


In [3]:
import numpy as nm
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix
X= nm.array([[1,0],[2,0],[3,0],[6,0],[6,0],[7,0],[10,0],[11,0]])
print("Dataset with 8 points: \n",X,"\n Size: ",len(X))
y = nm.array([0,0,1,1,1,0,0,0])
print("\nClass label for datasetX Y:",y)
x_train, x_test, y_train, y_test= train_test_split(X, y, test_size=0.25, random_state=0)  
print("\nTrain Data X: \n", x_train)
print("\nTrain Data label Y:", y_train)

stand_scalar= StandardScaler()
x_train= stand_scalar.fit_transform(x_train)
x_test= stand_scalar.transform(x_test)

classifier= KNeighborsClassifier(n_neighbors=3)

classifier.fit(x_train, y_train)

y_pred= classifier.predict(x_test)
print('\nPredicted Classs labels for testing data Y:',y_pred)

confusion_matrix_result = confusion_matrix(y_test, y_pred)
print("\nConfusion Matrix\n",confusion_matrix_result)

total_value = sum(sum(confusion_matrix_result))

accuracy=(confusion_matrix_result[0,0]+confusion_matrix_result[1,1])
print ('\nAccuracy : ', accuracy)

sensitivity = confusion_matrix_result[1,1]/(confusion_matrix_result[1,0]+confusion_matrix_result[1,1])
print("Sensitivity : ", sensitivity )
                                            
specificity = confusion_matrix_result[0,0]/(confusion_matrix_result[0,0]+confusion_matrix_result[0,1])


print("Specificity : ", specificity)
                                            
                                            

Dataset with total 8 points: 
 [[ 1  0]
 [ 2  0]
 [ 3  0]
 [ 6  0]
 [ 6  0]
 [ 7  0]
 [10  0]
 [11  0]] 
 Size:  8

Class label for the datasetX Y: [0 0 1 1 1 0 0 0]

Training Data X: 
 [[ 2  0]
 [11  0]
 [ 6  0]
 [ 1  0]
 [ 7  0]
 [ 6  0]]

Training Data label Y: [0 0 1 0 0 1]

Predicted Classs labels for testing data Y: [0 0]

Confusion Matrix
 [[1 0]
 [1 0]]

Accuracy :  1
Sensitivity :  0.0
Specificity :  1.0
